services:
  pec:
    container_name: esus
    image: esus:${ESUS_IMAGE}
    pull_policy: build
    platform: linux/amd64
    volumes:
      - ${ESUS_VOLUME_PATH}/${ESUS_IMAGE}/opt:/opt/e-SUS
      - ${ESUS_VOLUME_PATH}/${ESUS_IMAGE}/backups:/backups
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_PASSWORD: esus
        ESUS_DOWNLOAD_URL: ${ESUS_DOWNLOAD_URL}
    environment:
      - TZ=America/Recife
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=esus
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=esus
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - "2740:8080"
      - "2741:80"
      - "2742:443"
    depends_on:
      - db
  db:
    container_name: esus_db
    image: postgres:14-alpine
    command: postgres -c password_encryption=md5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=esus
      - POSTGRES_DB=esus
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=md5
    ports: 
      - "2743:5432" 
    volumes:
      - ${ESUS_VOLUME_PATH}/${ESUS_IMAGE}/db:/var/lib/postgresql/data
